In [0]:
import numpy as np

In [0]:
lst1 = [1,2,3]
lst2 = [3,1,2]
lst1+lst2

In [0]:
ex = "a"
ey = "b"
ex+ey

In [0]:
gen1 = (r for r in range(8))
num = 0
for g in gen1:
    num = num + g
num

In [0]:
type (gen1)

In [0]:
lst1 = [1.,2.,3.]
array1 = np.array(lst1)

array2 =np.array([3,1,2])

In [0]:
array1

In [0]:
type(array1)

In [0]:
array1[1] = 6.5

In [0]:
print(array1)
print(array2)

In [0]:
array1.dtype

In [0]:
print("array1 added by array1: ",array2+array1)

print("array1 multiplied by array1: ",array2*array1)
#Division:
print("array1 divided by array1: ",array2/array1)
#Raising an array to the power of another array:
print("array1 raised to the power of array1: ",array2**array1)
# [1.  6.5 3. ]
# [3 1 2]

In [0]:
lst_5=[i for i in range(1,6)]
print(lst_5)
array_5=np.array(lst_5)

#Sine operation:

print("Sine: ",np.sin(array_5))
#Logarithm operation:
print("Natural logarithm: ",np.log(array_5))
print("Base-10 logarithm: ",np.log10(array_5))
print("Base-2 logarithm: ",np.log2(array_5))
#Exponential operation:
print("Exponential: ",np.exp(array_5))


In [0]:
lin_smp = np.linspace(0,50,11)
print("11 linearly spaced numbers between 0 and 5: ",lin_smp)
# (0, 5] = beginning at 0 and up to and including 5

In [0]:
len(lin_smp)

In [0]:
list_2D = [[1,2,3],[4,5,6],[7,8,9]]
mat1 = np.array(list_2D)
print("Type/Class of this object:",type(mat1))
print("Here is the matrix\n----------\n",mat1,"\n----------")



In [0]:
type(mat1)

In [0]:
mat1[2][0]

In [0]:
array2

In [0]:
#Even tuples can be converted to multi-dimensional arrays:
tuple_2D = np.array([(1.5,2,3), (4,5,6),(7,8,9)])
print(tuple_2D)

In [0]:
mat_tuple = np.array(tuple_2D)
#mat_tuple
print (mat_tuple)

In [0]:
#array([3, 1, 2])
print("array1 added by array1: ",array2+mat_tuple)
print("array1 multiplied by array1: ",array2*mat_tuple)
#Division:
print("array1 divided by array1: ",array2/mat_tuple)
#Raising an array to the power of another array:
print("array1 raised to the power of array1: ",array2**mat_tuple)

In [0]:
print("array1 added by array1: ",mat1**tuple_2D)

In [0]:
array2
array3 = np.array([[1],[2],[3]])
array3

In [0]:
#print("array1 added by array1: ",list_2D+mat_tuple)

print("array1 multiplied by array1: ",list_2D*array3)
#Division:
print("array1 divided by array1: ",list_2D/array3)
#Raising an array to the power of another array:
print("array1 raised to the power of array1: ",list_2D**array3)

In [0]:
#but the size will be 6, as 6 = 3x2.
#Print the dimension of the matrix using ndim:
print("Dimension of this matrix: ",mat1.ndim,sep='') 
#Print the size of the matrix using size:
print("Size of this matrix: ", mat1.size,sep='') 
#Print the shape of the matrix using shape:
print("Shape of this matrix: ", mat1.shape,sep='')
#Print the data type of the matrix using dtype:
print("Data type of this matrix: ", mat1.dtype,sep='')
#

In [0]:
#Often, you may have to create matrices filled with zeroes, ones, random numbers, or ones in the diagonal:
print("Vector of zeros: ",np.zeros(5))
print("Matrix of zeros: ",np.zeros((3,4)))


In [0]:
print("Vector of ones: ",np.ones(4))
print("Matrix of ones: ",np.ones((4,2)))
print("Matrix of 5’s: ",5*np.ones((3,3)))



In [0]:
num_samp = np.ones((4,2))
type(num_samp)

In [0]:
num_samp

In [0]:
print("Identity matrix of dimension 2:",np.eye(2))
print("Identity matrix of dimension 4:",np.eye(4))
print("Random matrix of shape (4,3):\n",np.random.randint(low=1,high=10,size=(4,3)))


In [0]:
import numpy as np
npeye = np.eye(4)
nprand =np.random.randint(low=1,high=10,size=(4,4))
npeye * nprand


In [0]:
nprand

In [0]:
#The following functions accomplish those tasks. Execute the following code:
a = np.random.randint(1,100,30)
a

In [0]:
help(np.random.randint)

In [0]:
arr = np.arange(0,11)
arr

In [0]:
#print("Array:",arr)
print("Element at 7th index is:", arr[7])
print("Elements from 3rd to 5th index are:", arr[3:6])
print("Elements up to 4th index are:", arr[:4])
print("Elements from last backwards are:", arr[2:6:-2])
# -1
#Elements from last backwards are: [10  9  8  7  6  5  4  3  2  1  0]
print("3 Elements from last backwards are:", arr[-1:-6:-2])
print("All Elements:", arr[:])

In [0]:
57*30

In [0]:
mat = np.array(np.random.randint(10,100,15))
print(mat)
matrs = mat.reshape(5,3)
print(matrs)
print("Matrix of random 2-digit numbers\n",mat)
print ("\nFifth Element", mat[4])

print ("\nElements greater than 50\n", mat[mat>50])


In [0]:
#NumPy arrays operate just like mathematical matrices, and the operations are performed element-wise:
mat1 = np.random.randint(1,10,9).reshape(3,3)
array_mat1 = mat1.reshape(9,1)
mat2 = np.random.randint(1,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n",mat2)
print("\nAddition\n", mat1+mat2)
print("\nMultiplication\n", mat1*mat2)
print("\nDivision\n", mat1/mat2)
print("\nLineaer combination: 3*A - 2*B\n", 3*mat1-2*mat2)
print("\nAddition of a scalar (100)\n", 100+mat1)
print("\nLinear Exponentiation, matrix cubed here\n", mat1**3)
print("\nExponentiation, square root using ‘pow’ function\n",pow(mat1,0.5))


In [0]:
txt = input("what string?")
repeat = int(input("how many times?"))
print(txt*repeat)

In [0]:
print('a\tb\nc\td\n\"e\\')


In [0]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print("Matrix a\n",a)
print("Matrix b\n",b)
print("Vertical stacking\n",np.vstack((a,b)))
print("Horizontal stacking\n",np.hstack((a,b)))
print("Vertical stacking alt \n",np.vstack((b,a)))
print("Horizontal stacking alt \n",np.hstack((b,a)))


In [0]:
print("\nExponentiation, square root using ‘pow’ function\n",pow(mat1,mat2))


In [0]:
# list = []
# Matrix a
#  [[1 2]
#  [3 4]]
# Matrix b
#  [[5 6]
#  [7 8]]
c = np.empty((2,2), dtype=a.dtype)
print(c)
c[0::2] = a[0]
c[1::2] = b[0]
c

In [0]:
results = {
    'Question 1': [10, 15, 17, 32, 26],
    'Question 2': [26, 22, 29, 10, 13],
    'Question 3': [35, 37, 7, 2, 19],
    'Question 4': [32, 11, 9, 15, 33],
    'Question 5': [21, 29, 5, 5, 40],
    'Question 6': [8, 19, 5, 30, 38]
}
print([np.cumsum(np.array(v)) for v in results.values()])

In [0]:
import matplotlib.pyplot as plt
plt.get_cmap('RdYlGn')

In [0]:
category_colors = plt.get_cmap('RdYlGn')(
    np.linspace(0.15, 0.85, np.array(list(results.values())).shape[1]))
category_colors    

In [0]:

category_names = ['Strongly disagree', 'Disagree',
                  'Neither agree nor disagree', 'Agree', 'Strongly agree']
foo = zip(category_names, category_colors)                  
[f for f in enumerate(foo)]

In [0]:
[f for f in enumerate(foo)]

In [0]:
import numpy as np
import matplotlib.pyplot as plt


category_names = ['Strongly disagree', 'Disagree',
                  'Neither agree nor disagree', 'Agree', 'Strongly agree']
results = {
    'Question 1': [10, 15, 17, 32, 26],
    'Question 2': [26, 22, 29, 10, 13],
    'Question 3': [35, 37, 7, 2, 19],
    'Question 4': [32, 11, 9, 15, 33],
    'Question 5': [21, 29, 5, 5, 40],
    'Question 6': [8, 19, 5, 30, 38]
}


def survey(results, category_names):
    """
    Parameters
    ----------
    results : dict
        A mapping from question labels to a list of answers per category.
        It is assumed all lists contain the same number of entries and that
        it matches the length of *category_names*.
    category_names : list of str
        The category labels.
    """
    labels = list(results.keys())
    data = np.array(list(results.values()))
    data_cum = data.cumsum(axis=1)
    category_colors = plt.get_cmap('RdYlGn')(
        np.linspace(0.15, 0.85, data.shape[1]))

    fig, ax = plt.subplots(figsize=(9.2, 5))
    ax.invert_yaxis()
    ax.xaxis.set_visible(False)
    ax.set_xlim(0, np.sum(data, axis=1).max())

    for i, (colname, color) in enumerate(zip(category_names, category_colors)):
        widths = data[:, i]
        starts = data_cum[:, i] - widths
        rects = ax.barh(labels, widths, left=starts, height=0.5,
                        label=colname, color=color)

        r, g, b, _ = color
        text_color = 'white' if r * g * b < 0.5 else 'darkgrey'
        #ax.bar_label(rects, label_type='center', color=text_color)
    ax.legend(ncol=len(category_names), bbox_to_anchor=(0, 1),
              loc='lower left', fontsize='small')

    return fig, ax


survey(results, category_names)
plt.show()

In [0]:
153**2

In [0]:
ax.bar_label?

In [0]:
np.array(list(results.values())).cumsum(axis=1)
#'Question 1': [10, 15, 17, 32, 26],

In [0]:
plt.get_cmap('RdYlGn')(
        np.linspace(0.15, 0.85, np.array(list(results.values())).cumsum(axis=1).shape[1]))

In [0]:
for w in enumerate(zip(category_names, category_colors)): print(w)